baseURL = "https://untivoyage.netlify.app/"
languageCode = "fr-fr"
title = "UnTi Voyage à Vélo"

theme = "bloggeri"
DefaultContentLanguage = "fr"
googleAnalytics = "UA-123-45"
disqusShortname = "untivoyage"
RemovePathAccents = true
PreserveTaxonomyNames = false
[permalinks]
    blog = "/blog/:filename/"
    
paginate = 4

[taxonomies]
  category = "categories"
  voyages = "voyages"

[related]
    threshold = 0
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "categories"
        weight = 100
    
    [[related.indices]]
        name = "voyages"
        weight = 130

    [[related.indices]]
        name = "date"
        weight = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    description = "Mon petit site de voyages à vélo"
    author = "Didier Dumortier"
    authorImage = "/images/didier.jpeg"

[[menu.main]]
  name = "A propos"
  url = "/a-propos"
  weight = 4

[[menu.main]]
  name = "Voyages"
  url = "/voyages"
  weight = 3

[[menu.main]]
  name = "Blog"
  url = "/blog"
  weight = 1

[[menu.main]]
    name = "Catégories"
    url = "/categories"
    weight = 2

[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 10

[[menu.social]]
    name = "GitHub"
    url = "https://github.com/did1979"
    pre = "<i class='fab fa-github'></i>"

[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/didier.dumortier"
    pre = "<i class='fab fa-twitter'></i>"

[[menu.footer]]
  name = "A propos"
  url = "/a-propos"

[[menu.footer]]
  name = "Mentions légales"
  url = "/mentions-legales"

[[menu.footer]]
  name = "Contact"
  url = "/contact"
