[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
<<<<<<< HEAD
HUGO_VERSION = "0.62.2"
=======
HUGO_VERSION = "0.65.0"
>>>>>>> a64f250c3ef3a41e788ceaab7003f3ba94117260
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
<<<<<<< HEAD
HUGO_VERSION = "0.62.2"
=======
HUGO_VERSION = "0.65.0"
>>>>>>> a64f250c3ef3a41e788ceaab7003f3ba94117260
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
<<<<<<< HEAD
HUGO_VERSION = "0.61.0"
=======
HUGO_VERSION = "0.65.0"
>>>>>>> a64f250c3ef3a41e788ceaab7003f3ba94117260

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
<<<<<<< HEAD
HUGO_VERSION = "0.62.2"
=======
HUGO_VERSION = "0.65.0"
>>>>>>> a64f250c3ef3a41e788ceaab7003f3ba94117260

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
